### ISSUE TITLE
After end turn button was pressed once, when "enter" was pressed, the end turn button would be activate.

### ISSUE THREAD

**Issue by CutUpTheEastWind** [guladam/deck_builder_tutorial#19]
There was no "ui_accept" related event in the code, how could I fix this. It also happend with the finish version uploaded.

**Comment by CutUpTheEastWind** [comment]
This issue seem caused by the engine, when "enter" was pressed, the last button pressed would be activate again.

After I open the deck view and exit, "enter" no more cause "end turn" button activate.

**Comment by guladam** [comment]
Hey,

I don't understand the issue here. Can you elaborate?
"ui_accept" is a default action defined in all Godot projects.

![ui_accept](https://github.com/user-attachments/assets/0841cfc4-3e9e-44fb-b103-78b397e2aa52)

**Comment by CutUpTheEastWind** [comment]
https://github.com/user-attachments/assets/3c3a025a-3bee-4a6e-9987-4c417825c3ad

I just upload a video to show the issue.

**Comment by CutUpTheEastWind** [comment]
if I clear all input from "ui_accept", that won't happened. What cause that?

**Comment by guladam** [comment]
Thanks for the clarification. 

This is not a bug, it's just how UI works in Godot. UI focus is a feature which lets you control and navigate the UI via keyboard or gamepad. By default, a node gets focused when you click on it and remains in focus. You don't see this because we didn't set a different StyleBox for focusing the buttons. Try adding a new StyleBox to the theme resource and test again, you'll immediately see what's going on:

![image](https://github.com/user-attachments/assets/4a2cbf7a-c409-4a12-adcd-d1f42551ecfb)

If you don't want this behaviour, just set the focus_mode to *None* on any Button Node:

![image](https://github.com/user-attachments/assets/504c2f9e-1abb-495a-8bde-542cee7260eb)

For further reading:
[Relevant docs here](https://docs.godotengine.org/en/stable/tutorials/ui/gui_navigation.html)
