### ISSUE TITLE
Playing the “Trickster” card allows you to play the drawn card even without the required mana.

### ISSUE THREAD

**Issue by LePadawan** [guladam/deck_builder_tutorial#21]
Hello,

First of all, thank you for your awesome course! :)

I noticed a bug from the bonus video "Adding Extra Content to a Roguelike Deckbuilder in Godot (Bonus Episode)" : 

Playing the “Trickster” card allows you to play the drawn card even without the required mana.

How to reproduce :

Play the trickster with low mana (0 for example) and play the card drawn. If you play it immediatly, it will count as a played card.
However, if you cancel by right-clicking then the check for the mana cost is done and you cannot play the card anymore.

An example after playing the trickster card with 0 mana:

![bug_deckbuilder](https://github.com/user-attachments/assets/c234e977-97d8-42b2-bbff-f0b9cf7854d0)

As you can see, I can play the drawn card (and indeed it is wrongly playable, not just a visual bug).

Bye!

**Comment by guladam** [comment]
Hey, thanks for submitting this. I'll look into it as soon as I can and get back to you :)

**Comment by guladam** [comment]
Hey,

Turns out this bug wasn't related to the Trickster card or the CardDrawEffect at all.
See if you set the Warrior's max mana to 0, all cards will be playable after drawing.

That's because the *playable* property on the CardUI won't update until the mana of the player changes.
One line of code fixes this in this commit:

https://github.com/guladam/deck_builder_tutorial/commit/693133b47af43e85b4457f6ad31ccefee15df826

Thanks for sharing! :)
